import { useCallback, useEffect, useMemo, useState } from 'react'
import { Activity, BookOpen, ChevronRight, CircleHelp, Database, KeyRound, LayoutDashboard, RefreshCw, Settings2, ShieldCheck, SlidersHorizontal, Trash2, Upload, Download, RotateCcw } from 'lucide-react'
import { Button } from './components/ui/button'
import { Card } from './components/ui/card'
import { Badge } from './components/ui/badge'
import { Switch } from './components/ui/switch'
import './index.css'

type Json = Record<string, unknown>
type Credential = { name?: string; auth_index?: string; disabled?: boolean; type?: string }
type Setting = { label: string; description: string; path: string; key: string; kind?: 'boolean' | 'number' | 'text' }
const initialKey = localStorage.getItem('management-key') ?? ''
const settings: Setting[] = [
  { label: 'Debug logging', description: 'Verbose diagnostics for local troubleshooting.', path: '/debug', key: 'debug', kind: 'boolean' },
  { label: 'Log to file', description: 'Persist logs to the configured runtime directory.', path: '/logging-to-file', key: 'logging-to-file', kind: 'boolean' },
  { label: 'Request retries', description: 'Attempts before a request is failed over.', path: '/request-retry', key: 'request-retry', kind: 'number' },
  { label: 'Retry credentials', description: 'Maximum credentials tried for one request.', path: '/max-retry-credentials', key: 'max-retry-credentials', kind: 'number' },
  { label: 'Retry interval', description: 'Delay between credential retries.', path: '/max-retry-interval', key: 'max-retry-interval', kind: 'number' },
  { label: 'Force model prefix', description: 'Apply the configured model prefix behavior.', path: '/force-model-prefix', key: 'force-model-prefix', kind: 'boolean' },
  { label: 'Routing strategy', description: 'Credential selection strategy for requests.', path: '/routing/strategy', key: 'strategy', kind: 'text' },
  { label: 'Proxy URL', description: 'Optional outbound proxy for upstream traffic.', path: '/proxy-url', key: 'proxy-url', kind: 'text' },
]

function App() {
  const [key, setKey] = useState(initialKey)
  const [config, setConfig] = useState<Json>({})
  const [credentials, setCredentials] = useState<Credential[]>([])
  const [apiKeys, setApiKeys] = useState<string[]>([])
  const [copilot, setCopilot] = useState<Json>({})
  const [tab, setTab] = useState('Overview')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [notice, setNotice] = useState('')
  const [newApiKey, setNewApiKey] = useState('')

  const api = useCallback(async (path: string, init?: RequestInit): Promise<unknown> => {
    const response = await fetch(`/v0/management${path}`, { ...init, headers: { 'x-management-key': key, ...(init?.headers ?? {}) } })
    if (!response.ok) throw new Error(`${response.status} ${response.statusText}`)
    return response.json()
  }, [key])
  const load = useCallback(async () => {
    if (!key) return
    setLoading(true); setError('')
    try {
      const [rawConfig, rawFiles, rawKeys, rawCopilot, ...rawSettings] = await Promise.all([api('/config'), api('/auth-files'), api('/api-keys'), api('/copilot'), ...settings.map(setting => api(setting.path).catch(() => ({})))])
      const merged = { ...((rawConfig as Json) ?? {}) }; settings.forEach((setting, index) => { const value = (rawSettings[index] as Json)[setting.key]; if (value !== undefined) merged[setting.key] = value }); setConfig(merged); setCredentials(((rawFiles as Json).files as Credential[]) ?? []); setApiKeys((((rawKeys as Json)['api-keys']) as string[]) ?? []); setCopilot((rawCopilot as Json) ?? {})
      localStorage.setItem('management-key', key); setNotice('Connected to the admin listener')
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Management API unavailable') }
    finally { setLoading(false) }
  }, [api, key])
  useEffect(() => { void load() }, [load])
  const active = credentials.filter(c => !c.disabled).length
  const update = async (path: string, value: unknown, keyName: string) => { try { await api(path, { method: 'PUT', headers: {'content-type':'application/json'}, body: JSON.stringify({ value }) }); setConfig(c => ({ ...c, [keyName]: value })); setNotice('Saved') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Save failed') } }
  const nav = [{ name: 'Overview', icon: LayoutDashboard }, { name: 'Credentials', icon: KeyRound }, { name: 'Runtime', icon: SlidersHorizontal }, { name: 'API keys', icon: ShieldCheck }, { name: 'Integrations', icon: Database }]
  const visibleSettings = useMemo(() => settings.filter(s => tab === 'Runtime' || s.label === 'Routing strategy' || s.label === 'Proxy URL'), [tab])

  async function upload(file: File) { const body = new FormData(); body.append('file', file); try { await api('/auth-files', { method:'POST', body }); await load(); setNotice('Credential uploaded') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Upload failed') } }
  async function removeCredential(name: string) { try { await api(`/auth-files?name=${encodeURIComponent(name)}`, { method:'DELETE' }); await load(); setNotice('Credential removed') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Delete failed') } }
  async function setDisabled(credential: Credential) { const disabled = !credential.disabled; try { await api('/auth-files/status', { method:'PATCH', headers:{'content-type':'application/json'}, body: JSON.stringify({ name: credential.name, auth_index: credential.auth_index, disabled }) }); await load() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Status update failed') } }
  async function downloadCredential(name: string) { try { const response = await fetch(`/v0/management/auth-files/download?name=${encodeURIComponent(name)}`, { headers: { 'x-management-key': key } }); if (!response.ok) throw new Error(`${response.status} ${response.statusText}`); const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Download failed') } }
  async function addKey() { if (!newApiKey.trim()) return; try { await api('/api-keys', { method:'PATCH', headers:{'content-type':'application/json'}, body: JSON.stringify({ old: '', new: newApiKey.trim() }) }); setApiKeys([...apiKeys, newApiKey.trim()]); setNewApiKey(''); setNotice('API key added') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Add failed') } }
  async function deleteKey(value: string) { try { await api(`/api-keys?value=${encodeURIComponent(value)}`, { method:'DELETE' }); setApiKeys(apiKeys.filter(k => k !== value)); setNotice('API key removed') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Delete failed') } }
  async function refreshCopilot() { const files = (copilot.files as Credential[] | undefined) ?? []; const authIndex = files[0]?.auth_index; if (!authIndex) { setNotice('No Copilot credential to refresh'); return } try { await api('/copilot/refresh', { method:'POST', headers:{'content-type':'application/json'}, body: JSON.stringify({ auth_index: authIndex }) }); await load(); setNotice('Copilot credential refreshed') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Copilot refresh failed') } }

  return <div className="console-shell"><header className="topbar"><div className="brand"><div className="brand-mark">∿</div><div>Operator console<small>private runtime control</small></div></div><div className="top-actions"><input className="key-input" type="password" aria-label="Management key" placeholder="management key" value={key} onChange={e => setKey(e.target.value)} onKeyDown={e => e.key === 'Enter' && void load()} /><Button onClick={() => void load()}><RefreshCw size={13} /> {loading ? 'Syncing' : 'Connect'}</Button></div></header><div className="layout"><aside className="sidebar"><div className="nav-label">Workspace</div><nav className="nav">{nav.map(item => { const Icon = item.icon; return <button key={item.name} className={tab === item.name ? 'active' : ''} onClick={() => setTab(item.name)}><Icon size={15} />{item.name}<ChevronRight size={13} style={{marginLeft:'auto', opacity: tab === item.name ? .8 : 0}} /></button> })}</nav><div className="sidebar-note"><strong><ShieldCheck size={13} style={{verticalAlign:'-2px', marginRight:5}} />Private by default</strong>Management traffic stays on the admin listener. API clients keep using the same stable endpoints.</div></aside><main className="main"><div className="heading-row"><div><div className="eyebrow">{tab}</div><h1>{tab === 'Overview' ? 'A clear view of your proxy.' : tab}</h1><p className="lede">Manage the same controls and resources exposed by the management API, from one operator surface.</p></div><div className="status-pill"><span className="dot" />{loading ? 'syncing' : error ? 'attention' : key ? 'connected' : 'key required'}</div></div>{error && <Card className="panel alert">{error}</Card>}{notice && <div className="notice">{notice}</div>}{!key && <Card className="panel"><div className="panel-title">Connect to your runtime</div><p className="lede" style={{marginTop:8}}>Enter the management key above, then press Connect.</p></Card>}{tab === 'Overview' && <Overview config={config} credentials={credentials} active={active} onUsage={value => void update('/usage-statistics-enabled', value, 'usage-statistics-enabled')} />}{tab === 'Credentials' && <Credentials credentials={credentials} onUpload={upload} onDelete={removeCredential} onToggle={setDisabled} onDownload={downloadCredential} onRefresh={() => void load()} />}{tab === 'Runtime' && <Runtime settings={visibleSettings} config={config} onUpdate={update} />}{tab === 'API keys' && <ApiKeys keys={apiKeys} value={newApiKey} setValue={setNewApiKey} onAdd={() => void addKey()} onDelete={deleteKey} />}{tab === 'Integrations' && <Integrations copilot={copilot} onRefresh={() => void load()} />}</main></div></div>
}

function Overview({ config, credentials, active, onUsage }: { config: Json; credentials: Credential[]; active: number; onUsage: (value: boolean) => void }) { return <><div className="grid"><Card className="stat"><div className="stat-label">Active credentials</div><div className="stat-value">{active}</div><div className="stat-hint">{credentials.length} loaded total</div></Card><Card className="stat"><div className="stat-label">Concurrency</div><div className="stat-value">{String(config['max-concurrency'] ?? '—')}</div><div className="stat-hint">request ceiling</div></Card><Card className="stat"><div className="stat-label">Retries</div><div className="stat-value">{String(config['request-retry'] ?? '—')}</div><div className="stat-hint">attempts per request</div></Card><Card className="stat"><div className="stat-label">Routing</div><div className="stat-value" style={{fontSize:20}}>{String(config.strategy ?? '—')}</div><div className="stat-hint">selection strategy</div></Card></div><div className="section-grid"><Card className="panel"><div className="panel-header"><div className="panel-title">Credential health</div><div className="panel-meta">{credentials.length} records</div></div>{credentials.slice(0,5).map((c, i) => <div className="credential-row" key={`${c.name}-${i}`}><div><div className="credential-name">{c.name ?? 'Unnamed credential'}</div><div className="credential-sub">{c.auth_index ?? c.type ?? 'provider credential'}</div></div><Badge tone={c.disabled ? 'amber' : 'green'}>{c.disabled ? 'disabled' : 'ready'}</Badge></div>)}{credentials.length === 0 && <div className="empty">No credentials loaded. Open Credentials to upload one.</div>}</Card><Card className="panel"><div className="panel-header"><div className="panel-title">Runtime controls</div><Activity size={15} color="#79d6c1" /></div><div className="toggle-row"><div><div className="toggle-title">Usage collection</div><div className="toggle-desc">Keep lightweight usage stats for this console.</div></div><Switch checked={Boolean(config['usage-statistics-enabled'])} onClick={() => onUsage(!Boolean(config['usage-statistics-enabled']))} /></div><div className="toggle-row"><div><div className="toggle-title">Debug logging</div><div className="toggle-desc">Verbose diagnostics for local troubleshooting.</div></div><Badge tone={config.debug ? 'amber' : 'green'}>{config.debug ? 'on' : 'off'}</Badge></div></Card></div></> }
function Credentials({ credentials, onUpload, onDelete, onToggle, onDownload, onRefresh }: { credentials: Credential[]; onUpload: (file: File) => void; onDelete: (name: string) => void; onToggle: (credential: Credential) => void; onDownload: (name: string) => void; onRefresh: () => void }) { return <Card className="panel"><div className="panel-header"><div><div className="panel-title">Auth files</div><div className="panel-meta">Manage provider credentials used by the proxy</div></div><div style={{display:'flex', gap:8}}><label className="button button-primary"><Upload size={13} /> Upload<input type="file" hidden onChange={e => e.target.files?.[0] && onUpload(e.target.files[0])} /></label><Button onClick={onRefresh}><RotateCcw size={13} /> Reload</Button></div></div>{credentials.map((c, i) => <div className="credential-row" key={`${c.name}-${i}`}><div><div className="credential-name">{c.name ?? 'Unnamed credential'}</div><div className="credential-sub">{c.auth_index ?? c.type ?? 'provider credential'}</div></div><div style={{display:'flex', alignItems:'center', gap:8}}><Badge tone={c.disabled ? 'amber' : 'green'}>{c.disabled ? 'disabled' : 'ready'}</Badge><Button onClick={() => onToggle(c)}>{c.disabled ? 'Enable' : 'Disable'}</Button>{c.name && <Button onClick={() => onDownload(c.name!)}><Download size={13} /></Button>}<Button onClick={() => c.name && onDelete(c.name)}><Trash2 size={13} /></Button></div></div>)}{credentials.length === 0 && <div className="empty">Upload a JSON auth file to get started.</div>}</Card> }
function Runtime({ settings, config, onUpdate }: { settings: Setting[]; config: Json; onUpdate: (path: string, value: unknown, key: string) => void }) { return <div className="settings-list">{settings.map(s => <Card className="panel setting" key={s.path}><div><div className="panel-title">{s.label}</div><div className="toggle-desc">{s.description}</div></div>{s.kind === 'boolean' ? <Switch checked={Boolean(config[s.key])} onClick={() => onUpdate(s.path, !Boolean(config[s.key]), s.key)} /> : <input className="setting-input" value={String(config[s.key] ?? '')} onChange={e => onUpdate(s.path, s.kind === 'number' ? Number(e.target.value) : e.target.value, s.key)} />}</Card>)}</div> }
function ApiKeys({ keys, value, setValue, onAdd, onDelete }: { keys: string[]; value: string; setValue: (value: string) => void; onAdd: () => void; onDelete: (value: string) => void }) { return <Card className="panel"><div className="panel-header"><div><div className="panel-title">API keys</div><div className="panel-meta">Keys accepted by the public API listener</div></div><div style={{display:'flex', gap:8}}><input className="setting-input" placeholder="new key" value={value} onChange={e => setValue(e.target.value)} /><Button variant="primary" onClick={onAdd}>Add key</Button></div></div>{keys.map(k => <div className="credential-row" key={k}><span className="credential-sub">{k}</span><Button onClick={() => onDelete(k)}><Trash2 size={13} /></Button></div>)}{keys.length === 0 && <div className="empty">No API keys configured.</div>}</Card> }
function Integrations({ copilot, onRefresh }: { copilot: Json; onRefresh: () => void }) { const files = (copilot.files as Credential[] | undefined) ?? []; const connected = files.length > 0; return <Card className="panel"><div className="panel-header"><div><div className="panel-title">Copilot integration</div><div className="panel-meta">Optional provider connection managed by the existing API</div></div><Button onClick={onRefresh}><RefreshCw size={13} /> Refresh token</Button></div><div className="credential-row"><span className="credential-sub">Status</span><Badge tone={connected ? 'green' : 'amber'}>{connected ? `${files.length} credential${files.length === 1 ? '' : 's'} connected` : 'not connected'}</Badge></div>{files.map(file => <div className="credential-row" key={file.auth_index ?? file.name}><div><div className="credential-name">{file.name ?? 'Copilot credential'}</div><div className="credential-sub">{file.auth_index ?? 'missing auth index'}</div></div><Badge tone="green">ready</Badge></div>)}<p className="lede" style={{marginTop:18}}>Device authorization remains available through the `/v0/management/copilot/*` endpoints for custom clients.</p></Card> }

import { createRoot } from 'react-dom/client'
createRoot(document.getElementById('root')!).render(<App />)
